### PR TITLE
Add open source license screen #106

### LINKED ISSUE #106: Add open source license screen
## Kind (Required)

- Improvement

 ## Overview (Required)

- This screen is placed in the following location.
- https://github.com/DroidKaigi/conference-app-2021/issues/260
- You don't need to put a link on the about screen for this development.

 ## Links	

-

### PR DESCRIPTION
**Pull request by yoshida0261**
## Issue
- close #106

## Overview (Required)
- title says all
- use oss-licenses-plugin
  -  https://github.com/google/play-services-plugins/tree/master/oss-licenses-plugin

## Links
-

## Screenshot
Before | After
:--: | :--:
none |

### CODE REVIEW

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
Sorry, Could you fix CI build?

**Comment by takahirom** [comment]
Can you run `./gradlew uicomponent-compose:other:spotlessKotlinApply`? 
Perhaps there is a long line in the code. 👀 
image

**Comment by yoshida0261** [comment]
@takahirom 
OK. to correct🙇
I'm investigating the cause because it crashes when moving to the license activity

**Comment by yoshida0261** [comment]
This is what I think is the cause.🤔
>E/GmsClient: unable to connect to service: com.google.android.gms.oss.licenses.service.START on com.google.android.gms

This shouldn't matter
>ava.lang.RuntimeException: Parcel: unable to marshal value androidx.compose.runtime.SnapshotMutableStateImpl@d8a9fe0


>2021-03-12 13:27:37.278 1738-5012/? W/ActivityTaskManager: Tried to set launchTime (0) < mLastActivityLaunchTime (94057260)
2021-03-12 13:27:37.301 1738-5012/? W/ActivityManager: Unable to start service Intent { act=com.google.android.gms.oss.licenses.service.START pkg=com.google.android.gms } U=0: not found
2021-03-12 13:27:37.302 1738-5012/? W/ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@a2c8acd
2021-03-12 13:27:37.303 25065-25106/io.github.droidkaigi.feeder.debug E/GmsClient: unable to connect to service: com.google.android.gms.oss.licenses.service.START on com.google.android.gms
2021-03-12 13:27:37.342 1738-5012/? W/ActivityManager: Unable to start service Intent { act=com.google.android.gms.oss.licenses.service.START pkg=com.google.android.gms } U=0: not found
2021-03-12 13:27:37.343 1738-5012/? W/ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@ecfbf82
2021-03-12 13:27:37.361 1738-5012/? W/ActivityManager: Unable to start service Intent { act=com.google.android.gms.oss.licenses.service.START pkg=com.google.android.gms } U=0: not found
2021-03-12 13:27:37.362 1738-3084/? W/ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@b3e51ce
2021-03-12 13:27:37.343 25065-25106/io.github.droidkaigi.feeder.debug I/chatty: uid=10395(io.github.droidkaigi.feeder.debug) GoogleApiHandle identical 1 line
2021-03-12 13:27:37.363 25065-25106/io.github.droidkaigi.feeder.debug E/GmsClient: unable to connect to service: com.google.android.gms.oss.licenses.service.START on com.google.android.gms
2021-03-12 13:27:37.364 25065-25259/io.github.droidkaigi.feeder.debug W/OssLicensesLoader: Error getting license list from service: com.google.android.gms.common.api.ApiException: 17: API: OssLicensesService.API is not available on this device. Connection failed with: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
2021-03-12 13:27:37.395 1738-1876/? I/ActivityTaskManager: Displayed io.github.droidkaigi.feeder.debug/com.google.android.gms.oss.licenses.OssLicensesMenuActivity: +127ms
2021-03-12 13:27:37.425 4060-4060/? I/GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3340 
2021-03-12 13:27:37.427 4060-4060/? I/GoogleInputMethodService: GoogleInputMethodService.onStartInput():1929 
2021-03-12 13:27:37.496 1016-1098/? I/CHRE: @ 161224.238: [AR] still: 95.686271
2021-03-12 13:27:37.865 25065-25065/io.github.droidkaigi.feeder.debug D/AndroidRuntime: Shutting down VM
--------- beginning of crash
2021-03-12 13:27:37.868 25065-25065/io.github.droidkaigi.feeder.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.droidkaigi.feeder.debug, PID: 25065
    java.lang.RuntimeException: Parcel: unable to marshal value androidx.compose.runtime.SnapshotMutableStateImpl@d8a9fe0
        at android.os.Parcel.writeValue(Parcel.java:1885)
        at android.os.Parcel.writeList(Parcel.java:1092)
        at android.os.Parcel.writeValue(Parcel.java:1832)
        at android.os.Parcel.writeMapInternal(Parcel.java:943)
        at android.os.Parcel.writeMap(Parcel.java:925)
        at android.os.Parcel.writeValue(Parcel.java:1797)
        at android.os.Parcel.writeMapInternal(Parcel.java:943)
        at android.os.Parcel.writeMap(Parcel.java:925)
        at android.os.Parcel.writeValue(Parcel.java:1797)
        at android.os.Parcel.writeList(Parcel.java:1092)
        at android.os.Parcel.writeValue(Parcel.java:1832)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:975)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
        at android.os.Bundle.writeToParcel(Bundle.java:1303)
        at android.os.Parcel.writeBundle(Parcel.java:1044)
        at android.os.Parcel.writeValue(Parcel.java:1801)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:975)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
        at android.os.Bundle.writeToParcel(Bundle.java:1303)
        at android.os.Parcel.writeBundle(Parcel.java:1044)
        at android.os.Parcel.writeValue(Parcel.java:1801)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:975)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
        at android.os.Bundle.writeToParcel(Bundle.java:1303)
        at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4389)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
`

**Comment by yoshida0261** [comment]
The above issue now works after pulling the latest code😅

**Review by tomoya0x00 — APPROVED** [review]
Thank you for your tough work 🙇 Let's merge ❤️

**Pull request merged**
