### PR TITLE
Fix status bar transparent

### LINKED ISSUE #100: Fix status bar transparent
## Kind (Required)
- Improvement

 ## Overview (Required)

-  Currently
image

- DroidKaigi 2020
image

 ## Links	

-

### PR DESCRIPTION
**Pull request by a25max**
## Issue
- close #100 

## Overview (Required)
- changed status bar color

## Links
-

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
Thank you! I think the status bar is black, but last year's app was translucent and I would like to do the same, is that possible?

**Comment by takahirom** [comment]
image

**Comment by a25max** [comment]
Is it correct? @takahirom 
device-2021-03-02-121939

**Comment by takahirom** [comment]
Thank you for listening to my request! It's LGTM!

**Review by takahirom — APPROVED** [review]

**Pull request merged**
