### PR TITLE
Revert "[iOS] Create xcframework with Gradle"

### PR DESCRIPTION
**Pull request by ry-itto**
Reverts DroidKaigi/conference-app-2021#469

### CODE REVIEW

**Comment by ry-itto** [comment]
After this merged, I'll revert this PR

**Comment by takahirom** [comment]
I am trying this 👀 
https://github.com/DroidKaigi/conference-app-2021/pull/478

**Comment by ry-itto** [comment]
> I am trying this 👀

OK! Thanks 🙏🏼

**Review by takahirom — APPROVED** [review]
Thank you! We can not fix this immediately. So we should merge this 🙏

**Pull request merged**
