### PR TITLE
Keep selected tab through rotation at FeedScreen

### LINKED ISSUE #127: Keep selected tab through screen rotation
## Kind (Required)

- Improvement

 ## Overview (Required)

- Since this is the state of FeedScreen, it may be possible to keep it in ViewModel

 ## Links	

-

### PR DESCRIPTION
**Pull request by Index197511**
## Issue
- close #127 

## Overview (Required)
- Tab selection returns to Home every time when the screen is rotated, so it is now keeped in the ViewModel.

## Links
-

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by Index197511** [comment]
When an item is selected from the Drawer, FeedScreen receives the selected tab as InitialSelectedTab, but how do I propagate this as the initial state to the ViewModel?

**Comment by Index197511** [comment]
Currently, I have implemented it only in FeedScreen, but should I implement it in OtherScreen as well?

**Comment by mhidaka** [comment]
👀

**Comment by mhidaka** [comment]
It's good question💡
@Index197511 Don't worries, It is walcome thing that you'll just implement the FeedScreen to improve keeping selected tab within rotation☎

By the way, we're glad that the number of contributors will increase if you create a new issue for other screens to fix the same problem.

**Comment by Index197511** [comment]
Thank you!
I've finished implementation and make an issue to implement the selected tabs from the Drawer and something similar in OtherScreen.

**Comment by Index197511** [comment]
@mhidaka 
Thank you!
I've finished implementation and make an issue to implement the selected tabs from the Drawer and something similar in OtherScreen.

**Comment by mhidaka** [comment]
Great! Thank you for your additional work. and The review of this PR is waiting for A reviewer in charge to get freetime. please wait a minite 😉

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
> When an item is selected from the Drawer, FeedScreen receives the selected tab as InitialSelectedTab, but how do I propagate this as the initial state to the ViewModel? @takahirom

How about this way?

```kotlin
    effectFlow.collectInLaunchedEffect { effect ->
        when (effect) {
            is FeedViewModel.Effect.ErrorMessage -> {
                scaffoldState.snackbarHostState.showSnackbar(
                    effect.appError.getReadableMessage(context)
                )
            }
        }
    }
    LaunchedEffect(initialSelectedTab) {
        dispatch(...)
    }
```

**Comment by Index197511** [comment]
It looks very good.
However, with this way, won't the LanchedEffect be called every time the screen is rotated and the Tab will be reset?

**Comment by Index197511** [comment]
It looks very good.
However, with this way, won't the LanchedEffect be called every time the screen is rotated and the Tab will be reset?
@takahirom

**Comment by takahirom** [comment]
I will check more 👀

**Comment by takahirom** [comment]
It was my mistake. Perhaps the selected tabs are unmanageable in this scope. 👀 
I'm very sorry, is it possible to move the tab management process to AppContent and use savedInstanceState()?

**Comment by Index197511** [comment]
It may take a while, but I'll try it.

**Comment by Index197511** [comment]
Would it be better to create another issue and implement it there? @takahirom

**Comment by takahirom** [comment]
I have assigned you to this issue. Therefore, you can add an implementation to this PR or issue another PR. 👍 
https://github.com/DroidKaigi/conference-app-2021/issues/198

**Comment by Index197511** [comment]
I'm thinking if I try to save FeedTabs within onSavedInstanceState, Activity must own selected tab in the FeedScreen. I'm not sure how to do this, as having a ViewModel in the Activity seems subtle.
@takahirom

**Comment by takahirom** [comment]
Can you use navigation? (I tried. but this is not fixed format commit)
https://github.com/DroidKaigi/conference-app-2021/commit/7a907ac9602267443265a912744d7c69ef121e48

**Comment by Index197511** [comment]
Thank you for your help!
I moved the SelectedTab that I had in ViewModel to Navigation.
It's working well.

**Comment by Index197511** [comment]
Thank you for your help! @takahirom 
I moved the SelectedTab that I had in ViewModel to Navigation.
It's working well.
I've finished implementation for this PR.

**Review by takahirom — APPROVED** [review]
Thank you for tackling 👍 LGTM

**Pull request merged**
