### PR TITLE
[iOS] transition to settingScreen

### LINKED ISSUE #501: [iOS] Transition to Setting Screen
## Kind (Required)

- Improvement

 ## Overview (Required)

- Please make transitioning to SettingScreen.
- Please implement without thinking about https://github.com/DroidKaigi/conference-app-2021/issues/493 once.

 ## Links	

-

### PR DESCRIPTION
**Pull request by Tech-Nayuta**
## Issue
- close #501
- pull request #527

## Overview (Required)
-

## Links
-

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by ry-itto** [comment]
Please specify close issue correctly. => #501 

And this PR has some conflicts. Please fix this.

**Comment by ostk0069** [comment]
@Tech-Nayuta 
Please fix conflicts 🙏

**Review by ry-itto — APPROVED** [review]
LGTM 👍🏼

**Comment by Tech-Nayuta** [comment]
Thank you!

**Pull request merged**
