### PR TITLE
feature / RobotItem for FeedList

### LINKED ISSUE #70: Can we implement robot item? 🤖
## Kind (Required)

- Improvement

 ## Overview (Required)

When the size of the article list is larger than the size of the screen, robot is displayed as the last item.

image

 ## Links	

-

### PR DESCRIPTION
**Pull request by felix925**
## Issue
- close #70 

## Overview (Required)
- If size of article list is larger than size of screen, show robot end of list.

## Links
- https://github.com/DroidKaigi/conference-app-2021/issues/70
- https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by tomoya0x00** [comment]
👀

**Comment by felix925** [comment]
@tomoya0x00 
Thank you for your review!!
I'll fix it.

**Comment by tomoya0x00** [comment]
Now, I'm checking ci warnings ...

**Comment by tomoya0x00** [comment]
@felix925 
Sorry, But it looks remaining a spotless warning.
Could you run `./gradlew :spotlessApply` again?  🙏 

I've checked that this warning can be solved by it.

image

**Comment by takahirom** [comment]
You can run spotlessApply from here 🙏 
image

**Comment by felix925** [comment]
@tomoya0x00 
@takahirom 
Thank you for your review and advices.
Sorry, I'm missing it. Now fixing.

**Comment by felix925** [comment]
I was fix it. Please review when you have a time.

**Review by takahirom — APPROVED** [review]
LGTM 👍

**Comment by felix925** [comment]
Thank you for your review and check!!

**Pull request merged**
