### PR TITLE
add proguard rules

### LINKED ISSUE #78: Proguard
## Kind (Required)

- Improvement

 ## Overview (Required)

- Make the appropriate proguard settings and enable obfuscation and optimization.

 ## Links	

-

### PR DESCRIPTION
**Pull request by RyuNen344**
## Issue
- close #78 

## Overview (Required)
- add kotlinx.serialization's rule
- I didn't add `flipper`'s rule
- any other need?

## Links
-

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by takahirom** [comment]
Thank you. Have you checked the release build? 👀

**Comment by RyuNen344** [comment]
>Thank you. Have you checked the release build?

yes!
I have verified this with a debug build with `minifyEnabled` enabled(and comment out flipper's code)

**Comment by takahirom** [comment]
Looks good 👍 

> I didn't add flipper's rule

Can I ask why didn't you add it? Didn't you add flipper because it's a debugging library? 🙋

**Comment by RyuNen344** [comment]
>Can I ask why didn't you add it? Didn't you add flipper because it's a debugging library? 

yes, I think debugging library not needs to add proguard rule.

what do you think about treat of debugging library?
(I'll do it if you tell me 🙋‍♂️)

**Comment by takahirom** [comment]
I was just asking that because I don't know why🙏
Thank you for your answer. I think so too 👍

**Review by takahirom — APPROVED** [review]
LGTM 💯

**Pull request merged**
