### PR TITLE
Show DroidKaigi logo instead of Toolbar text

### LINKED ISSUE #101: Show DroidKaigi logo instead of Toolbar text
## Kind (Required)

- Improvement

 ## Overview (Required)

- 
image
image

 ## Links	

- https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app?node-id=0%3A1

### PR DESCRIPTION
**Pull request by kwQt**
## Issue
- close #101

## Overview (Required)
- I added xml files and replaced Text with Image in TopAppBar.

## Screenshot
FeedScreen
Before | After
:--: | :--:
 | 

OtherScreen
Before | After
:--: | :--:
 |

### CODE REVIEW

**Review by takahirom — APPROVED** [review]
Looks great 👍

**Review by takahirom — APPROVED** [review]
Looks GREAT!! 🎨 Thank you!

**Comment by takahirom** [comment]
Sorry. Can you rebase or merge the main branch?

**Comment by takahirom** [comment]
Probably format is broken. And I fixed it 👀

**Comment by kwQt** [comment]
Thanks, I rebased this branch onto latest main.

**Comment by takahirom** [comment]
Thank you !

**Pull request merged**
