### PR TITLE
Use real API of staff and contributor API

### PR DESCRIPTION
**Pull request by takahirom**
## Issue
- close #ISSUE_NUMBER

## Overview (Required)
- 🎉 
image
image

## Links
-

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by takahirom** [comment]
@ry-itto FYR: Finally, we can use real API for contributors and staff! 🎉

**Comment by takahirom** [comment]
@ry-itto @ostk0069  
It seems that a little change is needed on the iOS side to display it. Can this branch handle it?
I think that this feature will motivate the contributors.
image

**Comment by ry-itto** [comment]
@takahirom 
> It seems that a little change is needed on the iOS side to display it. Can this branch handle it?

Yes, I think this branch can handle it 👍🏼 

> I think that this feature will motivate the contributors.

I think so too! I'll call about this contribution on Twitter 🙏🏼 

---
### About contribution
#### Points need to change (I think this is all)

```
- Change id type to Int
- Change property names
  - name -> username
  - url -> profileUrl
  - image -> iconUrl
```

#### About pull-request

Create Pull Request to `DroidKaigi2021/use-real-contributor-and-staff-api`

**Comment by takahirom** [comment]
Thank you for your cooperation! 🙏

**Pull request merged**
