### PR TITLE
Fix #425: using setDefaultNightMode

### LINKED ISSUE #425: Drawable-night is not accessible
**Overview (Required)**
- In the dark mode, images are not coming from the `drawable-nigth`. 

**Steps To Reproduce**

1. Go to Settings and change theme to dark
2. Go to about and see the image logo

**Expected behavior**
In the dark theme image should come from `drawable-nigth`

**Screenshots**

**Env:**
 - Device: Pixel XL
 - OS: @* API level

**Additional context**
Approaches solve:
1. We can introduce `RealAboutThisAppViewModel` and `AboutThisAppViewModel` and bring the ThemeRepository data to the `AboutThisApp` screen and use the view model in the `fun WhatIsDroidKaigiComponent` and based on theme, get the image. But, in this approach, we cannot access an image from `drawable-night`, so we need to rename the image to `logo_night` and put it in the drawable folder only. 
2. We can use `ContextCompat` and get the drawable, but then we need to get the drawable id and pass it to the `painterResource` which is a bit complex.

### PR DESCRIPTION
**Pull request by anandwana001**
## Issue
- close #425

## Overview (Required)
- Using of setDefaultNightMode

## Links
-

## Screenshot
Before | After
:--: | :--:
 | 

This also solving #344

### CODE REVIEW

**Comment by anandwana001** [comment]
@takahirom Please let me know, if this is a correct approach to fix this issue.

**Comment by takahirom** [comment]
I think there are good and bad things, but since the ViewModel will be in the form of directly operating the View, how about doing the following?

```kotlin
class MainActivity : AppCompatActivity() {
    private val appViewModel by viewModels<RealAppViewModel>()
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        WindowCompat.setDecorFitsSystemWindows(window, false)
        setup()
        appViewModel.state
            .onEach {
// ...
            }
            .launchIn(lifecycleScope)
    }
```

**Comment by anandwana001** [comment]
Using `setDefaultNightMode` will lead into activity recreation - https://medium.com/androiddevelopers/appcompat-v23-2-daynight-d10f90c83e94

**Comment by takahirom** [comment]
I'll take a look tomorrow :eyes:

**Comment by takahirom** [comment]
Now Activity is receated by config changes such as screen rotation. So that's fine.
Thank you for teaching me. 👍

**Review by takahirom — APPROVED** [review]
Thank you for raising the issue and solving it! 👍

**Pull request merged**
