### PR TITLE
[WIP]Use cpu architecture task for iOS test workflow

### PR DESCRIPTION
**Pull request by takahirom**
## Issue
- close #ISSUE_NUMBER

## Overview (Required)
-

## Links
-

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
@myihsan @watanavex 
The current approach may not run the test well 😭

**Comment by takahirom** [comment]
main branch

```
* What went wrong:
Task 'iosTest' is ambiguous in root project 'conference-app-2021'. Candidates are: 'iosTestBinaries', 'iosTestKlibrary', 'iosTestProcessResources'.
```

this branch (iosTest has runBlocking method 😭 )

```
> Task :data:db:compileTestKotlinIosX64 FAILED
e: /Users/runner/work/conference-app-2021/conference-app-2021/data/db/src/commonTest/kotlin/io/github/droidkaigi/feeder/data/TestUtil.kt: (3, 12): Expected function 'runBlocking' has no actual declaration in module <conference-app-2021.data:db_test> for Native
```

**Comment by takahirom** [comment]
For the time being, I will revert yesterday's changes.
https://github.com/DroidKaigi/conference-app-2021/pull/477#pullrequestreview-676844305

**Comment by myihsan** [comment]
@takahirom 
> main branch
> 
> ```
> * What went wrong:
> Task 'iosTest' is ambiguous in root project 'conference-app-2021'. Candidates are: 'iosTestBinaries', 'iosTestKlibrary', 'iosTestProcessResources'.
> ```
> 
> this branch (iosTest/ has runBlocking method 😭 )
> 
> ```
> > Task :data:db:compileTestKotlinIosX64 FAILED
> e: /Users/runner/work/conference-app-2021/conference-app-2021/data/db/src/commonTest/kotlin/io/github/droidkaigi/feeder/data/TestUtil.kt: (3, 12): Expected function 'runBlocking' has no actual declaration in module <conference-app-2021.data:db_test> for Native
> ```

This is a good sign.
Please try `iosX64Test.dependsOn(iosTest)` for all module with workaround. I have forgotten test targets💦

I was not able to test it on local since I have another unexpected issue that may be caused by my enviroument.

**Comment by watanavex** [comment]
Sorry I'm late checking.

iOS-Test workflow runs on an Intel Mac.
It cannot be run on Arm64 architecture.

The cause is machine of GitHub Actions😂

Thank you @myihsan❗️

**Pull request closed without merging**
