### PR TITLE
Implement ProgressTimeLatch for Compose

### LINKED ISSUE #108: Implement ProgressTimeLatch for Compose
## Kind (Required)

- Improvement

 ## Overview (Required)

- ProgressTimeLatch prevents the progress bar from flickering. Please search for more information. 

 ## Links	

-

### PR DESCRIPTION
**Pull request by sobaya-0141**
## Issue
- close #108

## Overview (Required)
- Implement ProgressTimeLatch

## Links
-

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
Thank you as always! 👍 

I'm sorry, it was a little different from what I was thinking.  It was a difficult issue to make a ProgressTimeLatch that can be used with Compose. 💦 
However, it may be better to implement it with ViewModel, 👍   
But, ProgressTimeLatch works regardless of the lifecycle of ViewModel, so I don't want to put it in ViewModel for a while. 💭 

I have a library I was making that works with coroutines scope. Is it possible to change this to return StateFlow by passing ViewModelScope?
https://github.com/takahirom/coroutines-progress-time-latch/blob/main/library/src/main/java/com/github/takahirom/coroutine/progress/time/latch/CoroutinesProgressTimeLatch.kt

**Comment by sobaya-0141** [comment]
Thank you for your review.

I'm it a try.

**Comment by sobaya-0141** [comment]
I fixed ProgressTimeLatch

But I am not Confidence

please review it

**Comment by takahirom** [comment]
Almost LGTM!! Thank you for trying code 🙏 
Can you apply ./gradlew uicomponent-compose:core:spotlessKotlinApply ?

**Comment by sobaya-0141** [comment]
I’m Done.
Final confirmation, please.:bow::bow::bow:

**Review by takahirom — APPROVED** [review]
Thank you! We try to use ProgressTimeLatch in ViewModel! 👍

**Pull request merged**
