### PR TITLE
Move androidX dependencies from android/build.gradle to Dep.kt

### LINKED ISSUE #68: Move AndroidX dependencies to Dep.kt
## Kind (Required)

- Improvement

 ## Overview (Required)

- There are some parts that specify direct compose dependencies, so I want to put them together in Dep.kt.
- However, do not replace the compose dependency as it will be done in #65 .

 ## Links	

-

### PR DESCRIPTION
**Pull request by Index197511**
## Issue
- close #68 

## Overview (Required)
- I put AndroidX dependencies in Dep.kt

## Links
-

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by tomoya0x00** [comment]
👀

**Review by tomoya0x00 — APPROVED** [review]
LGTM 💯 Thanks for your contribution!

**Comment by Index197511** [comment]
I've finished. please would somebody review it.

**Comment by tomoya0x00** [comment]
We'll merge this after ci passed 💪

**Pull request merged**
