### PR TITLE
Move androidx.appcompat:appcompat:1.2.0 to Dep.kt

### LINKED ISSUE #202: Move androidx.appcompat:appcompat:1.2.0 to Dep.kt
## Kind (Required)

- Improvement

 ## Overview (Required)

- The title says everything. Please see link 🙏 

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/f0267c32b8acb5f6f60a10e674c4cce858d9008d/uicomponent-compose/core/build.gradle#L47
- https://github.com/DroidKaigi/conference-app-2021/blob/main/buildSrc/src/main/java/Dep.kt#L19

### PR DESCRIPTION
**Pull request by akihiro-n**
## Issue
- close #202 

## Overview (Required)
- Move androidx.appcompat:appcompat:1.2.0 to Dep.kt

### CODE REVIEW

**Review by takahirom — APPROVED** [review]
Thank you for fast implementation!

**Comment by akihiro-n** [comment]
Thank you for the review!

**Comment by takahirom** [comment]
I don't know why but the build is failed.

Can you add a line break here? 🙏 

```kotlin
    object Compose {
        const val activity = "androidx.activity:activity-compose:1.3.0-alpha02"
        const val constraintLayout = // ← here
            "androidx.constraintlayout:constraintlayout-compose:1.0.0-alpha03"
```

**Comment by akihiro-n** [comment]
OK!!

**Comment by takahirom** [comment]
Thanks 🙏

**Pull request merged**
